/**
 * 🏆 PREMIUM US TECH & GADGET DROPSHIPPING PRODUCT DATABASE (20 ACTIVE ALIEXPRESS WINNERS)
 * 100% Pure Niche: Tech & Gadgets. Curated with active, guaranteed high-resolution, context-accurate Unsplash image URLs.
 */

export const featuredProducts = [
  {
    id: 1,
    name: "MagSafe 3-in-1 PowerStation Pro",
    category: "Trending Tech Drops",
    price: 59.99,
    oldPrice: 129.99,
    discount: "54%",
    image: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=800&q=80",
    tag: "Viral Product",
    badge: "Bestseller",
    rating: 4.9,
    reviews: 2847,
    stock: 48,
    description: "The ultimate minimalist charging hub for your Apple ecosystem. Fast-charge iPhone, Apple Watch, and AirPods simultaneously without cable clutter.",
    specs: ["15W MagSafe Fast Charge", "Qi-Compatible Smart Induction", "Aero-Grade Zinc Alloy", "Advanced Overheat Shield"],
    warranty: "2-Year Replacement Warranty"
  },
  {
    id: 2,
    name: "Anti-Gravity Levitating Humidifier",
    category: "Trending Tech Drops",
    price: 49.99,
    oldPrice: 99.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800&q=80",
    tag: "TikTok Trending",
    badge: "Viral Choice",
    rating: 4.8,
    reviews: 1934,
    stock: 31,
    description: "Defy physics with levitating water drops that travel upwards while purifying and humidifying your ambient air. A breathtaking setup centerpiece.",
    specs: ["Anti-Gravity Water Drop Flow", "Ultrasonic Cool Mist Purifier", "Built-in Smart LED Clock", "Auto-Shutdown Water Sensor"]
  },
  {
    id: 3,
    name: "Smart RGBIC TV Backlight Sync Kit",
    category: "Trending Tech Drops",
    price: 89.99,
    oldPrice: 179.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80",
    tag: "Setup Essential",
    badge: "Cinema Peak",
    rating: 4.9,
    reviews: 1845,
    stock: 18,
    description: "Immerse yourself completely in movies and games. The smart camera captures colors from your screen and instantly synchronizes the ambient LED strips behind your TV or monitor.",
    specs: ["Dynamic RGBIC Screen Color Sync", "1080p Smart Wide-Angle Camera", "Voice Enabled (Alexa/Google Home)", "16 Million Ambient Color Options"]
  },
  {
    id: 4,
    name: "Invisible Under-Desk Wireless Charger",
    category: "Trending Tech Drops",
    price: 54.99,
    oldPrice: 119.99,
    discount: "54%",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80",
    tag: "Minimalist Setup",
    badge: "Innovative Tech",
    rating: 4.9,
    reviews: 1102,
    stock: 42,
    description: "The ultimate clean-desk gadget. Mounts underneath your desk and charges your smartphone directly through wood, glass, or marble tables (up to 30mm thick).",
    specs: ["Under-Table Invisible Installation", "Fast-Charge Induction Technology", "Charges Through Wood/Glass/Plastic", "Complete Auto-Off Protection"]
  },
  {
    id: 5,
    name: "Viral Portable Mini Thermal Printer",
    category: "Trending Tech Drops",
    price: 29.99,
    oldPrice: 59.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&q=80",
    tag: "Viral Product",
    badge: "Back To School",
    rating: 4.7,
    reviews: 856,
    stock: 154,
    description: "Print custom photos, tags, labels, or notes instantly from your phone. Pocket-sized design uses heat-transfer technology, meaning zero ink is ever required.",
    specs: ["Zero-Ink Thermal Print Tech", "Bluetooth Companion Mobile App", "Compact Portable Travel Sizing", "Long-Life Rechargeable Battery"]
  },
  {
    id: 6,
    name: "3D Moving Sand Landscape Hourglass",
    category: "Trending Tech Drops",
    price: 39.99,
    oldPrice: 79.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1618005198143-e5283b519d7f?w=800&q=80",
    tag: "Aesthetic Decor",
    badge: "Desk Toy",
    rating: 4.8,
    reviews: 980,
    stock: 72,
    description: "Indulge in calming relaxation. Watch the colorful sand fall slowly through the liquid to create breathtaking, unique 3D desert and mountain scenes every single time it's rotated.",
    specs: ["Relaxing Motion Sand Flow Art", "High-Clarity Glass Circular Frame", "Modern Desktop Decorative Gift", "Fully Adjustable Air Flow Rates"]
  },
  {
    id: 7,
    name: "Aesthetic Smart Flame Diffuser",
    category: "Trending Tech Drops",
    price: 39.99,
    oldPrice: 79.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80",
    tag: "Aesthetic Decor",
    badge: "TikTok Winner",
    rating: 4.8,
    reviews: 4328,
    stock: 85,
    description: "Combine calming aromatherapy with a realistic, glowing flame simulation effect. Perfect for creating cozy, high-end relaxing bedroom aesthetics.",
    specs: ["Hyper-Realistic Flame Mist Simulation", "7-Color Intelligent LED Cycling", "Super Quiet Ultrasonic Humidifying", "Waterless Auto-Off Guard"]
  },
  {
    id: 8,
    name: "Aesthetic LED Flame Bluetooth Speaker",
    category: "Trending Tech Drops",
    price: 49.99,
    oldPrice: 99.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80",
    tag: "Setup Decor",
    badge: "TikTok Winner",
    rating: 4.9,
    reviews: 1302,
    stock: 35,
    description: "Enhance your ambient spaces. High-fidelity wireless Bluetooth speaker features a gorgeous flickering warm flame LED effect that looks like a beautiful tiki torch on your desk or patio.",
    specs: ["Warm LED Flickering Flame Effect", "Crystal Clear Stereo Audio Drivers", "IPX5 Rain & Splash Proof Guard", "Long Playtime Built-in Battery"]
  },
  {
    id: 9,
    name: "2-in-1 Smart Car Vacuum & Keyboard Duster",
    category: "Trending Tech Drops",
    price: 39.99,
    oldPrice: 79.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80",
    tag: "Problem Solver",
    badge: "Car Essential",
    rating: 4.8,
    reviews: 1420,
    stock: 94,
    description: "The ultimate clean-up tool. High-velocity electric air duster blows crumbs and dust out of mechanical keyboards, and acts as a powerful hand vacuum for car interiors.",
    specs: ["Dual Function Blow & Vacuum Modes", "90,000 RPM Super Power Motor", "Advanced Reusable HEPA Filter", "Long-Life Rechargeable Battery"]
  },
  {
    id: 10,
    name: "Crystal LED Sunset Ambient Lamp",
    category: "Trending Tech Drops",
    price: 24.99,
    oldPrice: 49.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&q=80",
    tag: "Aesthetic Decor",
    badge: "Impulse Buy",
    rating: 4.9,
    reviews: 3502,
    stock: 75,
    description: "Cast a gorgeous, warm sunset glow onto your walls. Create breathtaking aesthetic backgrounds for TikToks, photos, and relaxing bedroom mood-lighting.",
    specs: ["180-Degree Rotating Crystal Lens", "Remote App Color Adjustment", "Sturdy Weighted Safe Stand Base", "Ideal Studio-Style Backdrop Lamp"]
  },
  {
    id: 11,
    name: "Smart Cyberpunk RGB Glowing Tube Clock",
    category: "Smart Gadgets & Setup",
    price: 69.99,
    oldPrice: 149.99,
    discount: "53%",
    image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&q=80",
    tag: "Futuristic Setup",
    badge: "Cyberpunk Gold",
    rating: 4.9,
    reviews: 647,
    stock: 22,
    description: "Upgrade your desktop aesthetics. This glowing nixie tube-style digital clock features highly-customizable RGB lighting and simulated retro-futurism vacuum tubes.",
    specs: ["Simulated Vintage Nixie Glow Tubes", "Full RGB Color Customization", "Smart Time Alarm Controls", "Acrylic Cyberpunk Solid Base"]
  },
  {
    id: 12,
    name: "Transparent Cyberpunk 65W GaN Charger",
    category: "Smart Gadgets & Setup",
    price: 34.99,
    oldPrice: 69.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1610940882244-116086f6f9fc?w=800&q=80",
    tag: "Tech Essential",
    badge: "Futuristic GaN",
    rating: 4.8,
    reviews: 934,
    stock: 120,
    description: "Futuristic fast charging. Features a premium transparent casing showing off high-end internal circuitry and dynamic LED charging indicators.",
    specs: ["65W Multi-Port GaN fast charge", "Compact Travel Foldable Pins", "Futuristic Transparent Styling", "Smart Over-Current Safety Guard"]
  },
  {
    id: 13,
    name: "Smart Acoustic Anti-Snoring Device",
    category: "Smart Gadgets & Setup",
    price: 69.99,
    oldPrice: 149.99,
    discount: "53%",
    image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=800&q=80",
    tag: "Problem Solver",
    badge: "Restful Sleep",
    rating: 4.8,
    reviews: 673,
    stock: 22,
    description: "End snoring once and for all. This smart wearable device monitors acoustic breathing signatures and sends soft micro-vibrations to naturally adjust neck alignment, opening airways.",
    specs: ["Intelligent Sound & Vibration Triggers", "Comfortable Sleep-Grade Soft Band", "App Sleep Depth Tracking Reports", "Quick Snore Relief In 7 Days"]
  },
  {
    id: 14,
    name: "Smart UV-C Sanitizing Water Bottle",
    category: "Smart Gadgets & Setup",
    price: 29.99,
    oldPrice: 59.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80",
    tag: "Fitness Niche",
    badge: "Self-Cleaning",
    rating: 4.8,
    reviews: 432,
    stock: 90,
    description: "Pure water in 60 seconds. Built-in UV-C LED lights completely sterilize the inside of the bottle and destroy bacteria, odors, and bio-contaminants at the touch of a button.",
    specs: ["Deep Cleansing UV-C LED Light", "Double-Wall Thermal Insulation", "Keeps Cold 24H / Hot 12H", "Smart LED Water Temp Display"]
  },
  {
    id: 15,
    name: "Bluetooth Wireless Smart Sleep Mask",
    category: "Smart Gadgets & Setup",
    price: 24.99,
    oldPrice: 49.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
    tag: "Problem Solver",
    badge: "Deep Sleep",
    rating: 4.8,
    reviews: 2190,
    stock: 112,
    description: "Fall asleep faster in complete darkness. Combines a 100% total light blocking ergonomic sleep mask with ultra-thin, comfortable Bluetooth speakers to stream white noise or calming audio.",
    specs: ["100% Zero-Pressure Light Blocking", "Ultra-Thin Padded Comfort Speakers", "Bluetooth 5.2 Universal Audio Sync", "Washable Soft Memory Foam Fabric"]
  },
  {
    id: 16,
    name: "TikTok Gesture-Control LED Car Sign",
    category: "Smart Gadgets & Setup",
    price: 49.99,
    oldPrice: 99.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=80",
    tag: "TikTok Trending",
    badge: "Viral Sign",
    rating: 4.9,
    reviews: 1540,
    stock: 38,
    description: "Express yourself on the road. Show custom glowing hand-gestures or signs on your car's rear windshield using an interactive wireless remote control.",
    specs: ["Super-Bright LED Sign Panel", "Handheld Wireless Remote Control", "Simple Suction Cup Installation", "Massive Viral Appeal Niche"]
  },
  {
    id: 17,
    name: "Smart Biosecure Fingerprint Padlock",
    category: "Smart Gadgets & Setup",
    price: 34.99,
    oldPrice: 69.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80",
    tag: "Lock Securtiy",
    badge: "Keyless Secure",
    rating: 4.7,
    reviews: 846,
    stock: 80,
    description: "Say goodbye to keys and combinations. Unlock your gym locker, backpack, or gate instantly with a simple touch of your fingerprint.",
    specs: ["Ultra-Fast Fingerprint Sensor", "Holds 10 Separate Fingerprints", "IP65 Weather & Splash Proof", "Long-Life Rechargeable Battery"]
  },
  {
    id: 18,
    name: "Magnetic Floating Astronaut Speaker",
    category: "Smart Gadgets & Setup",
    price: 79.99,
    oldPrice: 169.99,
    discount: "53%",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80",
    tag: "Visual Speaker",
    badge: "Floating Music",
    rating: 4.9,
    reviews: 728,
    stock: 12,
    description: "A breathtaking acoustic centerpiece. Features a cute astronaut model that levitates and rotates in mid-air above a premium RGB lighted sound base.",
    specs: ["Magnetic Induction Levitation", "Full 360-Degree Stereo Audio", "Built-in Colorful RGB Lights", "Smart Touch Control Operations"]
  },
  {
    id: 19,
    name: "Minimalist Smart AirTag Key Organizer",
    category: "Smart Gadgets & Setup",
    price: 29.99,
    oldPrice: 59.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1621600411688-4be93fd68504?w=800&q=80",
    tag: "Minimalist Setup",
    badge: "Pocket Companion",
    rating: 4.8,
    reviews: 1624,
    stock: 140,
    description: "Never lose your keys again. Holds up to 8 keys in a silent, scratch-free premium vegan leather organizer pocket featuring an integrated slot for Apple AirTag.",
    specs: ["Integrated Apple AirTag Slot", "Quiet Anti-Rattle Key Lock", "Premium Vegan Sourced Leather", "Compact Travel Friendly Sizing"]
  },
  {
    id: 20,
    name: "Magnetic Self-Stirring Smart Mug",
    category: "Smart Gadgets & Setup",
    price: 24.99,
    oldPrice: 49.99,
    discount: "50%",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
    tag: "Desk Setup Must",
    badge: "Best Gift",
    rating: 4.7,
    reviews: 742,
    stock: 140,
    description: "Stir your coffee or tea instantly without spoons. Features magnetic induction stirring technology to perfectly blend milk, sugar, or powders with a simple button press.",
    specs: ["Fluid Dynamic Self-Stirring Tech", "Premium Double Stainless Steel", "Easy-Wash Detachable Agitator", "Thermal Heat-Lock Travel Lid"]
  }
];

export const reviews = [
  { id: 1, name: "John D.", location: "New York, USA", rating: 5, comment: "Absolutely stunning product! The quality exceeded my expectations. Shipping was incredibly fast.", date: "2 days ago" },
  { id: 2, name: "Sarah M.", location: "California, USA", rating: 5, comment: "Perfect for my home office setup. I've bought 3 items from Lumina and all are top notch.", date: "1 week ago" },
  { id: 3, name: "Michael R.", location: "Texas, USA", rating: 5, comment: "The anti-gravity humidifier is magic! My friends always ask about it. 10/10 recommend.", date: "3 days ago" },
  { id: 4, name: "Emma W.", location: "Florida, USA", rating: 4, comment: "Great gadgets, very modern design. Customer support was very helpful with my tracking.", date: "5 days ago" }
];
